'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BodyComp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Body Composition Calculator Release Notes:
        '''
        '''Note: Special markings key is located at bottom of release notes.
        '''
        '''
        '''Version 1.5.6.3 - INITIAL RELEASE
        '''
        '''Fixes: 
        '''     
        '''Bugs: 
        '''     
        '''     
        '''Special Markings: 
        '''An asterisk (*) before a bug signifies that it was found after the release notes were finalized for that build.
        '''A double asterisk (**) before a bug or fix signifies a feature that broke due to website maintenance.
        '''An asterisk and a capital P (*P) before a bug signifies a postponed bug.
        '''An asteris [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property resfiReleaseNotes() As String
            Get
                Return ResourceManager.GetString("resfiReleaseNotes", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property resicBCCAIO() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("resicBCCAIO", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property resicFFLogoMain() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("resicFFLogoMain", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property resicSecLogin() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("resicSecLogin", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property resimAbout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimAbout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimCopy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimCopy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimDelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimDelete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimGoLft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimGoLft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimGoRt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimGoRt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimHelp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimHelp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimHome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimHome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimLoading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimLoading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimLogin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimLogin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimNavBack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimNavBack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimNavForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimNavForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimNoGen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimNoGen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimOpenFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimOpenFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimPASTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimPASTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimPrint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimPrint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimPrintPreview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimPrintPreview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimRefresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimRefresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimSave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimSave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimUpdateNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimUpdateNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimUpdateOpt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimUpdateOpt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimUpdateReq() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimUpdateReq", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimUserFemale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimUserFemale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resimUserMale() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resimUserMale", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
